server:
  port: ${TEBEX_WEBHOOK_PORT:8080}
  shutdown: graceful

spring:
  application:
    name: tebex-microservice
  jmx:
    enabled: false

  # Security
  security:
    user:
      name: ${TEBEX_WEBHOOK_USERNAME:tebex}
      password: ${TEBEX_WEBHOOK_PASSWORD:tebex}

# Actuator
management:
    endpoints:
        web:
        exposure:
            include: "configprops,env,health,info,logfile,loggers,metrics,shutdown,threaddump"
    endpoint:
        health:
          show-details: always

# Logging
logging:
  file:
    name: logs/tebex-microservice.log
  level:
    web: ${TEBEX_WEBHOOK_LOGGING_LEVEL:INFO}